contentitemexportablefields:
  contentitemfields:
    fromServerVersion: ""
    itemVersion: ""
    packID: c029160a-c38b-4bb3-800e-38bcb7d072ff
    propagationLabels:
    - all
    toServerVersion: ""
id: 41014589-7fb0-4586-8e85-1ac9cc489e33
inputs:
- description: ""
  key: group-member
  playbookInputQuery: null
  required: false
  value: {}
name: 11-fortimanager-update-group
outputs: []
starttaskid: "0"
tasks:
  "0":
    id: "0"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "1"
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      id: bf606048-a21e-46d0-8c16-d67940d1ff8d
      iscommand: false
      name: ""
      version: -1
    taskid: bf606048-a21e-46d0-8c16-d67940d1ff8d
    timertriggers: []
    type: start
    view: |-
      {
        "position": {
          "x": 50,
          "y": 50
        }
      }
  "1":
    id: "1"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "2"
    note: false
    quietmode: 0
    scriptarguments:
      adom:
        simple: fw
      comment:
        simple: thanks
      member:
        simple: ${inputs.group-member}
      name:
        simple: xsoar
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      description: Create a new address group.
      id: 8ccacc74-7594-4654-8a4b-bb22e2055a9b
      iscommand: true
      name: group-update
      script: '|||fortimanager-address-group-update'
      type: regular
      version: -1
    taskid: 8ccacc74-7594-4654-8a4b-bb22e2055a9b
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 50,
          "y": 195
        }
      }
  "2":
    id: "2"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      id: 8bc72d47-fa89-4858-8058-2d880abb9400
      iscommand: false
      name: Done
      type: title
      version: -1
    taskid: 8bc72d47-fa89-4858-8058-2d880abb9400
    timertriggers: []
    type: title
    view: |-
      {
        "position": {
          "x": 50,
          "y": 370
        }
      }
version: -1
view: |-
  {
    "linkLabelsPosition": {},
    "paper": {
      "dimensions": {
        "height": 385,
        "width": 380,
        "x": 50,
        "y": 50
      }
    }
  }
