contentitemexportablefields:
  contentitemfields:
    definitionid: ""
    fromServerVersion: ""
    itemVersion: ""
    packID: 9c23ed3f-f561-49f2-8772-22dc518ce660
    propagationLabels:
    - all
    toServerVersion: ""
id: 3b49ab5f-479c-48f2-8e6d-b47c52ed3d47
inputs:
- description: ""
  key: agentid
  playbookInputQuery: null
  required: true
  value: {}
name: Hurukai - Get Artefact Logs
outputs: []
sourceplaybookid: 6eae88c6-c7cb-4f91-8d20-5d597be9b13d
starttaskid: "0"
tasks:
  "0":
    id: "0"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "9"
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      id: 909f4ed1-337d-4fb8-8049-f1a9886c6821
      iscommand: false
      name: ""
      version: -1
    taskid: 909f4ed1-337d-4fb8-8049-f1a9886c6821
    timertriggers: []
    type: start
    view: |-
      {
        "position": {
          "x": 600,
          "y": -980
        }
      }
  "3":
    id: "3"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    loop:
      exitCondition: ""
      iscommand: false
      max: 0
      wait: 1
    nexttasks:
      '#none#':
      - "7"
    note: false
    quietmode: 0
    scriptarguments:
      Ids:
        simple: ${Harfanglab.Job.ID}
      Interval:
        simple: "1"
      PollingCommandArgName:
        simple: ids
      PollingCommandName:
        simple: harfanglab-job-info
      Timeout:
        simple: "10"
      dt:
        simple: Harfanglab.Job.Info(val.Status !== 'finished').ID
    separatecontext: true
    skipunavailable: false
    task:
      brand: ""
      description: |-
        Use this playbook as a sub-playbook to block execution of the master playbook until a remote action is complete.
        This playbook implements polling by continuously running the command in Step \#2 until the operation completes.
        The remote action should have the following structure:

        1. Initiate the operation.
        2. Poll to check if the operation completed.
        3. (optional) Get the results of the operation.
      id: 08667dae-3eb1-4e2a-86c4-9037ef3ff285
      iscommand: false
      name: GenericPolling
      playbookId: GenericPolling
      type: playbook
      version: -1
    taskid: 08667dae-3eb1-4e2a-86c4-9037ef3ff285
    timertriggers: []
    type: playbook
    view: |-
      {
        "position": {
          "x": 700,
          "y": -260
        }
      }
  "5":
    id: "5"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      id: bb9a1782-9971-42cc-876a-a7c57777697d
      iscommand: false
      name: Done
      type: title
      version: -1
    taskid: bb9a1782-9971-42cc-876a-a7c57777697d
    timertriggers: []
    type: title
    view: |-
      {
        "position": {
          "x": 550,
          "y": 100
        }
      }
  "6":
    id: "6"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "3"
    note: false
    quietmode: 0
    scriptarguments:
      agent_id:
        simple: ${inputs.agentid}
    separatecontext: false
    skipunavailable: false
    task:
      brand: Hurukai
      description: Start a job to download Linux log files from a host (Linux)
      id: ed8cdc21-b524-4b46-80b8-aa7628bce215
      iscommand: true
      name: harfanglab-job-artefact-logs
      script: Hurukai|||harfanglab-job-artefact-logs
      type: regular
      version: -1
    taskid: ed8cdc21-b524-4b46-80b8-aa7628bce215
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 700,
          "y": -450
        }
      }
  "7":
    evidencedata:
      customfields: {}
      description:
        simple: Raw Linux log files
    id: "7"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "5"
    note: false
    quietmode: 0
    scriptarguments:
      job_id:
        simple: ${Harfanglab.Job.ID}
    separatecontext: false
    skipunavailable: false
    task:
      brand: Hurukai
      description: Get a hostname's log files from job results
      id: e32fe571-28c3-4c24-8edc-7642ad4bed52
      iscommand: true
      name: harfanglab-result-artefact-logs
      script: Hurukai|||harfanglab-result-artefact-logs
      type: regular
      version: -1
    taskid: e32fe571-28c3-4c24-8edc-7642ad4bed52
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 700,
          "y": -90
        }
      }
  "8":
    conditions:
    - condition:
      - - left:
            iscontext: true
            value:
              complex:
                accessor: Agent
                root: Harfanglab
                transformers:
                - args:
                    field:
                      value:
                        simple: ostype
                  operator: getField
          operator: isEqualString
          right:
            value:
              simple: linux
      label: linux
    id: "8"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#default#':
      - "5"
      linux:
      - "6"
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      id: 55fb113d-ea6b-418e-843b-8772550639a3
      iscommand: false
      name: Which platform is the agent running on ?
      type: condition
      version: -1
    taskid: 55fb113d-ea6b-418e-843b-8772550639a3
    timertriggers: []
    type: condition
    view: |-
      {
        "position": {
          "x": 600,
          "y": -670
        }
      }
  "9":
    id: "9"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "8"
    note: false
    quietmode: 0
    scriptarguments:
      agent_id:
        simple: ${inputs.agentid}
    separatecontext: false
    skipunavailable: false
    task:
      brand: Hurukai
      description: Get endpoint information from agent_id
      id: 5b114b33-ab5c-43c7-8c76-caf4f50d70e7
      iscommand: true
      name: harfanglab-get-endpoint-info
      script: Hurukai|||harfanglab-get-endpoint-info
      type: regular
      version: -1
    taskid: 5b114b33-ab5c-43c7-8c76-caf4f50d70e7
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 600,
          "y": -845
        }
      }
version: -1
view: |-
  {
    "linkLabelsPosition": {},
    "paper": {
      "dimensions": {
        "height": 1145,
        "width": 530,
        "x": 550,
        "y": -980
      }
    }
  }
