id: Claroty Incident
inputs: []
name: Claroty Incident
fromversion: 5.5.0
outputs: []
starttaskid: '0'
tasks:
  '0':
    id: '0'
    ignoreworker: false
    nexttasks:
      '#none#':
      - '1'
    note: false
    separatecontext: false
    task:
      brand: ''
      id: 8e712abe-51e2-4176-842f-47e507439fce
      iscommand: false
      name: ''
      version: -1
      description: ''
    taskid: 8e712abe-51e2-4176-842f-47e507439fce
    timertriggers: []
    type: start
    view: "{\n  \"position\": {\n    \"x\": 50,\n    \"y\": 50\n  }\n}"
    isautoswitchedtoquietmode: false
    isoversize: false
    quietmode: 0
    skipunavailable: false
  '1':
    id: '1'
    ignoreworker: false
    nexttasks:
      '#none#':
      - '3'
    note: false
    scriptarguments:
      fields:
        simple: all
      get_single_alert:
        simple: ${incident.clarotyresourceid}
    separatecontext: false
    task:
      brand: ''
      id: 7dc662b2-9e0b-4cb0-85e7-edeb0ecaf57c
      iscommand: true
      name: Claroty Get Alert Details test
      script: '|||claroty-query-alerts'
      type: regular
      version: -1
    taskid: 7dc662b2-9e0b-4cb0-85e7-edeb0ecaf57c
    timertriggers: []
    type: regular
    view: "{\n  \"position\": {\n    \"x\": 50,\n    \"y\": 195\n  }\n}"
    isautoswitchedtoquietmode: false
    isoversize: false
    quietmode: 0
    skipunavailable: false
  '3':
    id: '3'
    ignoreworker: false
    nexttasks:
      '#none#':
      - '4'
    note: false
    separatecontext: false
    task:
      brand: ''
      id: b52451f8-1d4a-4af4-89d2-04939791cd9b
      iscommand: false
      name: Manual Resolution
      type: regular
      version: -1
    taskid: b52451f8-1d4a-4af4-89d2-04939791cd9b
    timertriggers: []
    type: regular
    view: "{\n  \"position\": {\n    \"x\": 50,\n    \"y\": 370\n  }\n}"
    isautoswitchedtoquietmode: false
    isoversize: false
    quietmode: 0
    skipunavailable: false
  '4':
    id: '4'
    ignoreworker: false
    nexttasks:
      '#none#':
      - '5'
    note: false
    scriptarguments:
      resolve_as:
        simple: resolve
      selected_alerts:
        simple: ${Claroty.Alert.ResourceID}
    separatecontext: false
    task:
      brand: ''
      id: f7bf6bff-5b3d-43e3-8590-e90e08ebeee5
      iscommand: true
      name: Resolve Event in Claroty
      script: '|||claroty-resolve-alert'
      type: regular
      version: -1
    taskid: f7bf6bff-5b3d-43e3-8590-e90e08ebeee5
    timertriggers: []
    type: regular
    view: "{\n  \"position\": {\n    \"x\": 50,\n    \"y\": 545\n  }\n}"
    isautoswitchedtoquietmode: false
    isoversize: false
    quietmode: 0
    skipunavailable: false
  '5':
    id: '5'
    ignoreworker: false
    note: false
    scriptarguments:
      closeNotes:
        simple: Incident resolved
      id:
        simple: ${incident.id}
    separatecontext: false
    task:
      brand: Builtin
      id: 8d4db095-97c9-45f5-8c8c-4cd19d629c3b
      iscommand: true
      name: Close Investigation
      script: Builtin|||closeInvestigation
      type: regular
      version: -1
    taskid: 8d4db095-97c9-45f5-8c8c-4cd19d629c3b
    timertriggers: []
    type: regular
    view: "{\n  \"position\": {\n    \"x\": 50,\n    \"y\": 720\n  }\n}"
    isautoswitchedtoquietmode: false
    isoversize: false
    quietmode: 0
    skipunavailable: false
version: -1
view: "{\n  \"linkLabelsPosition\": {},\n  \"paper\": {\n    \"dimensions\": {\n \
  \     \"height\": 765,\n      \"width\": 380,\n      \"x\": 50,\n      \"y\": 50\n\
  \    }\n  }\n}"
tests:
- Claroty - Test
contentitemexportablefields:
  contentitemfields:
    propagationLabels:
    - all
