contentitemexportablefields:
  contentitemfields:
    definitionid: ''
    fromServerVersion: 5.0.0
    itemVersion: ''
    packID: 7f172158-1d1c-41cf-804e-379ac7b8c9c2
    propagationLabels:
    - all
    toServerVersion: ''
id: Claroty Incident
inputs: []
name: Claroty Incident
outputs: []
starttaskid: '0'
tasks:
  '0':
    id: '0'
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - '1'
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ''
      id: 8e712abe-51e2-4176-842f-47e507439fce
      iscommand: false
      name: ''
      version: -1
    taskid: 8e712abe-51e2-4176-842f-47e507439fce
    timertriggers: []
    type: start
    view: |-
      {
        "position": {
          "x": 50,
          "y": 50
        }
      }
  '1':
    id: '1'
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - '3'
    note: false
    quietmode: 0
    scriptarguments:
      fields:
        simple: all
      get_single_alert:
        simple: ${incident.clarotyresourceid}
    separatecontext: false
    skipunavailable: false
    task:
      brand: ''
      id: 7dc662b2-9e0b-4cb0-85e7-edeb0ecaf57c
      iscommand: true
      name: Claroty Get Alert Details test
      script: '|||claroty-query-alerts'
      type: regular
      version: -1
    taskid: 7dc662b2-9e0b-4cb0-85e7-edeb0ecaf57c
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 50,
          "y": 195
        }
      }
  '3':
    id: '3'
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - '4'
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ''
      id: b52451f8-1d4a-4af4-89d2-04939791cd9b
      iscommand: false
      name: Manual Resolution
      type: regular
      version: -1
    taskid: b52451f8-1d4a-4af4-89d2-04939791cd9b
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 50,
          "y": 370
        }
      }
  '4':
    id: '4'
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - '5'
    note: false
    quietmode: 0
    scriptarguments:
      resolve_as:
        simple: resolve
      selected_alerts:
        simple: ${Claroty.Alert.ResourceID}
    separatecontext: false
    skipunavailable: false
    task:
      brand: ''
      id: f7bf6bff-5b3d-43e3-8590-e90e08ebeee5
      iscommand: true
      name: Resolve Event in Claroty
      script: '|||claroty-resolve-alert'
      type: regular
      version: -1
    taskid: f7bf6bff-5b3d-43e3-8590-e90e08ebeee5
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 50,
          "y": 545
        }
      }
  '5':
    id: '5'
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    note: false
    quietmode: 0
    scriptarguments:
      closeNotes:
        simple: Incident resolved
      id:
        simple: ${incident.id}
    separatecontext: false
    skipunavailable: false
    task:
      brand: Builtin
      id: 8d4db095-97c9-45f5-8c8c-4cd19d629c3b
      iscommand: true
      name: Close Investigation
      script: Builtin|||closeInvestigation
      type: regular
      version: -1
    taskid: 8d4db095-97c9-45f5-8c8c-4cd19d629c3b
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 50,
          "y": 720
        }
      }
version: -1
view: |-
  {
    "linkLabelsPosition": {},
    "paper": {
      "dimensions": {
        "height": 765,
        "width": 380,
        "x": 50,
        "y": 50
      }
    }
  }
