args:
- isArray: true
  name: object_list
  required: true
- name: key_of_interest
  required: true
comment: Given a list of objects and a key found in each of those objects, return
  a unique list of values associated with that key.
commonfields:
  id: df9ec950-3519-4304-8e10-af1a95236720
  version: -1
contentitemexportablefields:
  contentitemfields:
    fromServerVersion: ""
    itemVersion: ""
    packID: 797d59fa-b7b2-4f4b-8006-7cf3726926c9
    propagationLabels:
    - all
    toServerVersion: ""
dockerimage: demisto/python3:3.9.8.24399
enabled: true
engineinfo: {}
name: DeduplicateValuesbyKey
outputs:
- contextPath: DeduplicatedValues
pswd: ""
runas: DBotWeakRole
runonce: false
script: ''
scripttarget: 0
subtype: python3
tags: []
type: python
