contentitemexportablefields:
  contentitemfields:
    propagationLabels:
    - all
description: Playbook can be run ad-hoc or as a Job to fetch results from Popular
  News sites
id: JOB - Popular News
inputs:
- description: ""
  key: KrebsOnSecurity
  playbookInputQuery:
  required: false
  value:
    simple: "true"
- description: ""
  key: ThreatPost
  playbookInputQuery:
  required: false
  value:
    simple: "true"
- description: ""
  key: TheHackerNews
  playbookInputQuery:
  required: false
  value:
    simple: "true"
name: 'JOB - Popular News '
outputs: []
quiet: true
starttaskid: "0"
tasks:
  "0":
    id: "0"
    ignoreworker: false
    nexttasks:
      '#none#':
      - "5"
      - "8"
      - "7"
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      id: 6a102a96-1df3-42cc-8015-4720f8ea8a4b
      iscommand: false
      name: ""
      version: -1
      description: ''
    taskid: 6a102a96-1df3-42cc-8015-4720f8ea8a4b
    timertriggers: []
    type: start
    view: |-
      {
        "position": {
          "x": 620,
          "y": -30
        }
      }
  "1":
    id: "1"
    ignoreworker: false
    nexttasks:
      '#none#':
      - "2"
    note: false
    quietmode: 0
    reputationcalc: 1
    scriptarguments:
      columns:
        simple: Article,Date,Link,Source
      context_path:
        simple: News
      grid_id:
        simple: customnewsgrid
      keys: {}
      overwrite: {}
      sort_by: {}
      unpack_nested_elements: {}
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      description: Creates a Grid table from items or key-value pairs.
      id: 5d407bc2-13e4-4d41-84b9-4e261f6dca2c
      iscommand: false
      name: Populate News to Grid
      scriptName: SetGridField
      type: regular
      version: -1
    taskid: 5d407bc2-13e4-4d41-84b9-4e261f6dca2c
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 695,
          "y": 695
        }
      }
  "2":
    id: "2"
    ignoreworker: false
    nexttasks:
      '#none#':
      - "3"
    note: false
    quietmode: 0
    scriptarguments:
      all:
        simple: "yes"
      index: {}
      key: {}
      keysToKeep: {}
      subplaybook: {}
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      description: Delete field from context
      id: d36d263c-4d65-410a-8872-bb30348a8650
      iscommand: false
      name: Delete Context
      scriptName: DeleteContext
      type: regular
      version: -1
    taskid: d36d263c-4d65-410a-8872-bb30348a8650
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 695,
          "y": 870
        }
      }
  "3":
    id: "3"
    ignoreworker: false
    nexttasks:
      '#none#':
      - "4"
    note: false
    quietmode: 0
    scriptarguments:
      assetid: {}
      closeNotes: {}
      closeReason: {}
      emailclassification: {}
      id: {}
      phishingsubtype: {}
    separatecontext: false
    skipunavailable: false
    task:
      brand: Builtin
      description: commands.local.cmd.close.inv
      id: 1ca39d91-2f14-4e97-89c7-aef61b72eb7b
      iscommand: true
      name: Close
      script: Builtin|||closeInvestigation
      type: regular
      version: -1
    taskid: 1ca39d91-2f14-4e97-89c7-aef61b72eb7b
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 695,
          "y": 1025
        }
      }
  "4":
    id: "4"
    ignoreworker: false
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      id: d9209834-4e51-4e8f-897f-fa13f55750e3
      iscommand: false
      name: Done
      type: title
      version: -1
      description: ''
    taskid: d9209834-4e51-4e8f-897f-fa13f55750e3
    timertriggers: []
    type: title
    view: |-
      {
        "position": {
          "x": 695,
          "y": 1240
        }
      }
  "5":
    conditions:
    - condition:
      - - left:
            iscontext: true
            value:
              simple: inputs.KrebsOnSecurity
          operator: isEqualString
          right:
            value:
              simple: "true"
      label: Get News from vendor
    id: "5"
    ignoreworker: false
    nexttasks:
      '#default#':
      - "11"
      Get News from vendor:
      - "6"
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      id: 76ed1385-ddba-4d11-831d-bfd864772cfa
      iscommand: false
      name: Get Vendor - Krebs on Security
      type: condition
      version: -1
    taskid: 76ed1385-ddba-4d11-831d-bfd864772cfa
    timertriggers: []
    type: condition
    view: |-
      {
        "position": {
          "x": 60,
          "y": 160
        }
      }
  "6":
    id: "6"
    ignoreworker: false
    nexttasks:
      '#none#':
      - "1"
    note: false
    quietmode: 0
    reputationcalc: 1
    separatecontext: false
    skipunavailable: false
    task:
      brand: Popular News
      id: 7877930a-1419-4563-88a5-6b79f3666c0a
      iscommand: true
      name: Get News Krebs on Security
      script: Popular News|||get-news-KrebsOnSecurity
      type: regular
      version: -1
    taskid: 7877930a-1419-4563-88a5-6b79f3666c0a
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": -70,
          "y": 370
        }
      }
  "7":
    conditions:
    - condition:
      - - left:
            iscontext: true
            value:
              simple: inputs.TheHackerNews
          operator: isEqualString
          right:
            value:
              simple: "true"
      label: Get News from vendor
    id: "7"
    ignoreworker: false
    nexttasks:
      '#default#':
      - "11"
      Get News from vendor:
      - "10"
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      id: 831c2fe7-529b-4b03-8f10-ad818dbd54fd
      iscommand: false
      name: Get Vendor - The Hacker News
      type: condition
      version: -1
    taskid: 831c2fe7-529b-4b03-8f10-ad818dbd54fd
    timertriggers: []
    type: condition
    view: |-
      {
        "position": {
          "x": 1140,
          "y": 160
        }
      }
  "8":
    conditions:
    - condition:
      - - left:
            iscontext: true
            value:
              simple: inputs.ThreatPost
          operator: isEqualString
          right:
            value:
              simple: "true"
      label: Get News from vendor
    id: "8"
    ignoreworker: false
    nexttasks:
      '#default#':
      - "11"
      Get News from vendor:
      - "9"
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      id: 8016cdaf-b21b-47a0-8319-c4751750b2fb
      iscommand: false
      name: Get Vendor - Threat Post
      type: condition
      version: -1
    taskid: 8016cdaf-b21b-47a0-8319-c4751750b2fb
    timertriggers: []
    type: condition
    view: |-
      {
        "position": {
          "x": 620,
          "y": 160
        }
      }
  "9":
    id: "9"
    ignoreworker: false
    nexttasks:
      '#none#':
      - "1"
    note: false
    quietmode: 0
    reputationcalc: 1
    separatecontext: false
    skipunavailable: false
    task:
      brand: Popular News
      id: 18e708ce-a0fd-443b-869a-5c2a5aa0cf2e
      iscommand: true
      name: Get News Threat Post
      script: Popular News|||get-news-Threatpost
      type: regular
      version: -1
    taskid: 18e708ce-a0fd-443b-869a-5c2a5aa0cf2e
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 380,
          "y": 370
        }
      }
  "10":
    id: "10"
    ignoreworker: false
    nexttasks:
      '#none#':
      - "1"
    note: false
    quietmode: 0
    reputationcalc: 1
    separatecontext: false
    skipunavailable: false
    task:
      brand: Popular News
      id: 7c780329-33b7-4a2c-8678-608492338079
      iscommand: true
      name: Get News The Hacker News
      script: Popular News|||get-news-TheHackerNews
      type: regular
      version: -1
    taskid: 7c780329-33b7-4a2c-8678-608492338079
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 920,
          "y": 370
        }
      }
  "11":
    id: "11"
    ignoreworker: false
    nexttasks:
      '#none#':
      - "1"
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      id: 43bb5429-654b-47b7-814d-a75b5e169294
      iscommand: false
      name: Skip Vendor
      type: title
      version: -1
      description: ''
    taskid: 43bb5429-654b-47b7-814d-a75b5e169294
    timertriggers: []
    type: title
    view: |-
      {
        "position": {
          "x": 1730,
          "y": 340
        }
      }
version: -1
view: |-
  {
    "linkLabelsPosition": {},
    "paper": {
      "dimensions": {
        "height": 1335,
        "width": 2180,
        "x": -70,
        "y": -30
      }
    }
  }
tests:
- No tests (auto formatted)
fromversion: 6.0.0
