contentitemexportablefields:
  contentitemfields:
    propagationLabels:
    - all
description: This playbook checks for content updates.
id: Check For Content Installation
inputs: []
name: Check For Content Installation
outputs: []
starttaskid: "0"
tasks:
  "0":
    id: "0"
    ignoreworker: false
    nexttasks:
      '#none#':
      - "1"
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      id: 4ffc1a83-fd5c-4f30-8dd3-fa34ad0f9295
      iscommand: false
      name: ""
      version: -1
      description: ''
    taskid: 4ffc1a83-fd5c-4f30-8dd3-fa34ad0f9295
    timertriggers: []
    type: start
    view: |-
      {
        "position": {
          "x": 50,
          "y": 50
        }
      }
  "1":
    id: "1"
    ignoreworker: false
    nexttasks:
      '#none#':
      - "2"
    note: false
    quietmode: 0
    scriptarguments:
      all:
        simple: "yes"
      index: {}
      key: {}
      keysToKeep: {}
      subplaybook:
        simple: auto
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      description: Delete field from context
      id: d71bee27-3b2b-496f-8ce5-d10cbdbd7892
      iscommand: false
      name: Delete Context
      scriptName: DeleteContext
      type: regular
      version: -1
    taskid: d71bee27-3b2b-496f-8ce5-d10cbdbd7892
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 50,
          "y": 195
        }
      }
  "2":
    id: "2"
    ignoreworker: false
    nexttasks:
      '#none#':
      - "3"
    note: false
    quietmode: 0
    scriptarguments:
      extend-context:
        simple: ContentDataCheck=response(val.updateAvailable==true).name
      uri:
        simple: /contentpacks/installed-expired
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      description: send HTTP GET requests
      id: e252f717-5265-48ab-82f3-4ac52980d0cf
      iscommand: true
      name: Check for updates
      script: '|||demisto-api-get'
      type: regular
      version: -1
    taskid: e252f717-5265-48ab-82f3-4ac52980d0cf
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 50,
          "y": 370
        }
      }
  "3":
    id: "3"
    ignoreworker: false
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      id: 34768bcf-d8a4-4a96-8710-55293eccc9b3
      iscommand: false
      name: Done
      type: title
      version: -1
      description: ''
    taskid: 34768bcf-d8a4-4a96-8710-55293eccc9b3
    timertriggers: []
    type: title
    view: |-
      {
        "position": {
          "x": 50,
          "y": 545
        }
      }
version: -1
view: |-
  {
    "linkLabelsPosition": {},
    "paper": {
      "dimensions": {
        "height": 560,
        "width": 380,
        "x": 50,
        "y": 50
      }
    }
  }
tests:
- No tests (auto formatted)
fromversion: 6.0.0
