args:
- description: Text to match against
  name: value
- description: Regex pattern to search (in Python)
  name: regex
  required: true
- description: The comma separated flags for pattern matching in regex. "dotall" (s),
    "multiline" (m), "ignorecase" (i) and "unicode" (u) are supported.
  name: flags
comment: Extraction of all matches from a specified regular expression pattern from
  a provided string.  Returns an array of values matched to the patterns.
commonfields:
  id: RegexExtractAllValues
  version: -1
contentitemexportablefields:
  contentitemfields:
    fromServerVersion: ""
dockerimage: demisto/python3:3.9.7.24076
enabled: true
name: RegexExtractAllValues
runas: DBotWeakRole
runonce: false
script: ''
scripttarget: 0
subtype: python3
tags:
- transformer
- string
type: python
fromversion: 6.0.0
tests:
- No tests (auto formatted)
