contentitemexportablefields:
  contentitemfields:
    propagationLabels:
    - all
id: CimTrak - Example - Analyze Intrusion
inputs:
- description: ""
  key: ""
  playbookInputQuery:
    daterange:
      fromdate: "0001-01-01T00:00:00Z"
      fromdatelicenseval: "0001-01-01T00:00:00Z"
      period:
        by: ""
        byfrom: ""
        byto: ""
        field: ""
        fromvalue:
        tovalue:
      todate: "0001-01-01T00:00:00Z"
    query: ""
    queryEntity: indicators
    results:
    runFromLastJobTime: true
  required: false
  value: {}
- description: ""
  key: lObjectDetailID
  playbookInputQuery:
  required: false
  value:
    complex:
      accessor: objectDetailId}
      root: ${incident.labels
- description: ""
  key: lParentID
  playbookInputQuery:
  required: false
  value:
    simple: ${incident.labels.parentId}
name: CimTrak - Example - Analyze Intrusion
outputs: []
starttaskid: "0"
tasks:
  "0":
    id: "0"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "1"
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      id: ef9587ba-8e1a-4ccb-8a97-f33ad91da0b6
      iscommand: false
      name: ""
      version: -1
      description: ''
    taskid: ef9587ba-8e1a-4ccb-8a97-f33ad91da0b6
    timertriggers: []
    type: start
    view: |-
      {
        "position": {
          "x": 50,
          "y": 50
        }
      }
  "1":
    id: "1"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "2"
    note: false
    quietmode: 1
    scriptarguments:
      ObjectDetailId:
        simple: ${inputs.lObjectDetailID}
    separatecontext: false
    skipunavailable: false
    task:
      brand: CimTrak
      description: Returns File Analysis by Object Detail ID
      id: 5aa047e5-9feb-46f2-8bc4-432f43f03bd7
      iscommand: true
      name: file-analysis-by-objectdetail-id
      script: CimTrak|||file-analysis-by-objectdetail-id
      type: regular
      version: -1
    taskid: 5aa047e5-9feb-46f2-8bc4-432f43f03bd7
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 50,
          "y": 230
        }
      }
  "2":
    conditions:
    - condition:
      - - left:
            iscontext: true
            value:
              complex:
                accessor: analysisResults.positives
                filters:
                - - left:
                      iscontext: true
                      value:
                        simple: CimTrak.FileAnalysis.analysisEngine
                    operator: isEqualString
                    right:
                      value:
                        simple: VirusTotal
                root: CimTrak.FileAnalysis
          operator: isEqualNumber
          right:
            value:
              simple: "0"
      - - left:
            iscontext: true
            value:
              complex:
                accessor: analysisResults.total
                filters:
                - - left:
                      iscontext: true
                      value:
                        simple: CimTrak.FileAnalysis.analysisEngine
                    operator: isEqualString
                    right:
                      value:
                        simple: VirusTotal
                root: CimTrak.FileAnalysis
          operator: greaterThanOrEqual
          right:
            value:
              simple: "50"
      label: File is not malicious
    - condition:
      - - left:
            iscontext: true
            value:
              complex:
                accessor: analysisResults.positives
                filters:
                - - left:
                      iscontext: true
                      value:
                        simple: CimTrak.FileAnalysis.analysisEngine
                    operator: isEqualString
                    right:
                      value:
                        simple: VirusTotal
                root: CimTrak.FileAnalysis
          operator: greaterThanOrEqual
          right:
            value:
              simple: "5"
      label: File is malicious
    id: "2"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#default#':
      - "11"
      File is malicious:
      - "4"
      File is not malicious:
      - "3"
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      description: "Gets a value and return it. This is to be used in playbook conditional tasks - get a value from incident field, label or context, and act accordingly. \nIf an array is returned. the first value will be the decision making value."
      id: 3cac13ac-04dc-4b34-8c02-10f286d3d0e1
      iscommand: false
      name: Check if file is malicious
      type: condition
      version: -1
    taskid: 3cac13ac-04dc-4b34-8c02-10f286d3d0e1
    timertriggers: []
    type: condition
    view: |-
      {
        "position": {
          "x": 50,
          "y": 410
        }
      }
  "3":
    id: "3"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "6"
    note: false
    quietmode: 0
    scriptarguments:
      hash:
        complex:
          accessor: md5
          root: CimTrak.FileAnalysis.analysisResults
          transformers:
          - args:
              prefix:
                value:
                  simple: 'MD5:'
              suffix: {}
            operator: concat
    separatecontext: false
    skipunavailable: false
    task:
      brand: CimTrak
      description: Add Hash to allow list
      id: c4e31325-7c27-4843-8d06-aeb559d1f670
      iscommand: true
      name: add-hash-allow-list MD5
      script: CimTrak|||add-hash-allow-list
      type: regular
      version: -1
    taskid: c4e31325-7c27-4843-8d06-aeb559d1f670
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 320,
          "y": 640
        }
      }
  "4":
    id: "4"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "9"
    note: false
    quietmode: 0
    scriptarguments:
      hash:
        complex:
          accessor: md5
          root: CimTrak.FileAnalysis.analysisResults
          transformers:
          - args:
              prefix:
                value:
                  simple: 'MD5:'
              suffix: {}
            operator: concat
    separatecontext: false
    skipunavailable: false
    task:
      brand: CimTrak
      description: Add Hash to deny list
      id: 75f42a4f-0901-44a5-8136-1cc9ba666a8d
      iscommand: true
      name: add-hash-deny-list MD5
      script: CimTrak|||add-hash-deny-list
      type: regular
      version: -1
    taskid: 75f42a4f-0901-44a5-8136-1cc9ba666a8d
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": -140,
          "y": 640
        }
      }
  "6":
    id: "6"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "7"
    note: false
    quietmode: 0
    scriptarguments:
      hash:
        complex:
          accessor: sha256
          root: CimTrak.FileAnalysis.analysisResults
          transformers:
          - args:
              prefix:
                value:
                  simple: 'SHA256:'
              suffix: {}
            operator: concat
    separatecontext: false
    skipunavailable: false
    task:
      brand: CimTrak
      description: Add Hash to allow list
      id: 816349f7-d10f-4104-8065-2a59d742904f
      iscommand: true
      name: add-hash-allow-list SHA256
      script: CimTrak|||add-hash-allow-list
      type: regular
      version: -1
    taskid: 816349f7-d10f-4104-8065-2a59d742904f
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 320,
          "y": 820
        }
      }
  "7":
    id: "7"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "8"
    note: false
    quietmode: 0
    scriptarguments:
      hash:
        complex:
          accessor: sha1
          root: CimTrak.FileAnalysis.analysisResults
          transformers:
          - args:
              prefix:
                value:
                  simple: 'SHA1:'
              suffix: {}
            operator: concat
    separatecontext: false
    skipunavailable: false
    task:
      brand: CimTrak
      description: Add Hash to allow list
      id: 1f70a13a-55c6-4ade-8d0d-5c3acf934aa4
      iscommand: true
      name: add-hash-allow-list SHA1
      script: CimTrak|||add-hash-allow-list
      type: regular
      version: -1
    taskid: 1f70a13a-55c6-4ade-8d0d-5c3acf934aa4
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 320,
          "y": 1000
        }
      }
  "8":
    id: "8"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    note: false
    quietmode: 0
    scriptarguments:
      ObjectDetaildIds:
        simple: ${inputs.lObjectDetailID}
    separatecontext: false
    skipunavailable: false
    task:
      brand: CimTrak
      description: Promote baseline files
      id: b4b445f8-9407-4f6d-8f9d-cf8c1c9de067
      iscommand: true
      name: promote-authoritative-baseline-files
      script: CimTrak|||promote-authoritative-baseline-files
      type: regular
      version: -1
    taskid: b4b445f8-9407-4f6d-8f9d-cf8c1c9de067
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 320,
          "y": 1180
        }
      }
  "9":
    id: "9"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "10"
    note: false
    quietmode: 0
    scriptarguments:
      hash:
        complex:
          accessor: sha256
          root: CimTrak.FileAnalysis.analysisResults
          transformers:
          - args:
              prefix:
                value:
                  simple: 'SHA256:'
              suffix: {}
            operator: concat
    separatecontext: false
    skipunavailable: false
    task:
      brand: CimTrak
      description: Add Hash to deny list
      id: 07f802aa-3b36-4f99-867c-9a57c30c9992
      iscommand: true
      name: add-hash-deny-list SHA256
      script: CimTrak|||add-hash-deny-list
      type: regular
      version: -1
    taskid: 07f802aa-3b36-4f99-867c-9a57c30c9992
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": -140,
          "y": 820
        }
      }
  "10":
    id: "10"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "12"
    note: false
    quietmode: 0
    scriptarguments:
      hash:
        complex:
          accessor: sha1
          root: CimTrak.FileAnalysis.analysisResults
          transformers:
          - args:
              prefix:
                value:
                  simple: 'SHA1:'
              suffix: {}
            operator: concat
    separatecontext: false
    skipunavailable: false
    task:
      brand: CimTrak
      description: Add Hash to deny list
      id: 58def19f-e321-4829-8b51-ff26a36ec419
      iscommand: true
      name: add-hash-deny-list SHA1
      script: CimTrak|||add-hash-deny-list
      type: regular
      version: -1
    taskid: 58def19f-e321-4829-8b51-ff26a36ec419
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": -140,
          "y": 1000
        }
      }
  "11":
    id: "11"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      description: "Review the incident to determine if the account activity is malicious.\n\nIf malicious, consider the following:\n* Quarantine the account/ endpoint \n* Revoke the account password\n* Query the account/ IPs logs in the SIEM\n* Block the external IPs in the firewall/ proxy\n* Check the account's privileges and change if needed"
      id: a762c9b2-95c6-459a-8fe0-398d9721ce0b
      iscommand: false
      name: Manually remediate  the incident
      type: regular
      version: -1
    taskid: a762c9b2-95c6-459a-8fe0-398d9721ce0b
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 780,
          "y": 580
        }
      }
  "12":
    id: "12"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "13"
    note: false
    quietmode: 0
    scriptarguments:
      ObjectSubType:
        simple: "10"
      ObjectType:
        simple: "3"
      ParentId:
        simple: ${inputs.lParentID}
    separatecontext: false
    skipunavailable: false
    task:
      brand: CimTrak
      description: Retrieves a list of objects.
      id: 7ac1cbc6-237b-4f70-80c6-58ef1844ec04
      iscommand: true
      name: Get Compliance Objects
      script: CimTrak|||get-objects
      type: regular
      version: -1
    taskid: 7ac1cbc6-237b-4f70-80c6-58ef1844ec04
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": -140,
          "y": 1180
        }
      }
  "13":
    id: "13"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    note: false
    quietmode: 0
    scriptarguments:
      objectId:
        simple: ${CimTrak.Objects.objectId}
    separatecontext: false
    skipunavailable: false
    task:
      brand: CimTrak
      description: Launch compliance scan for object and return results
      id: a7b0b201-9c61-445a-85ea-fe5cf878370a
      iscommand: true
      name: compliance-scan-with-summary
      script: CimTrak|||compliance-scan-with-summary
      type: regular
      version: -1
    taskid: a7b0b201-9c61-445a-85ea-fe5cf878370a
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": -140,
          "y": 1370
        }
      }
version: -1
view: |-
  {
    "linkLabelsPosition": {
      "2_11_#default#": 0.79
    },
    "paper": {
      "dimensions": {
        "height": 1415,
        "width": 1300,
        "x": -140,
        "y": 50
      }
    }
  }
tests:
- No tests (auto formatted)
fromversion: 6.0.0
description: Example on how to handle intrusion from CimTrak
