id: CimTrak - Example - Analyze Intrusion
version: -1
name: CimTrak - Example - Analyze Intrusion
starttaskid: "0"
tasks:
  "0":
    id: "0"
    taskid: 10ca1b00-1e5f-42eb-8c37-80ce4d9af7d2
    type: start
    task:
      id: 10ca1b00-1e5f-42eb-8c37-80ce4d9af7d2
      version: -1
      name: ""
      description: Entry
      iscommand: false
      brand: ""
      description: ''
    nexttasks:
      '#none#':
      - "1"
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 50,
          "y": 50
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
    isoversize: false
    isautoswitchedtoquietmode: false
  "1":
    id: "1"
    taskid: 3853df04-a7d7-42b7-8311-8ba335a58b68
    type: regular
    task:
      id: 3853df04-a7d7-42b7-8311-8ba335a58b68
      version: -1
      name: file-analysis-by-objectdetail-id
      description: Returns File Analysis by Object Detail ID
      script: CimTrak|||file-analysis-by-objectdetail-id
      type: regular
      iscommand: true
      brand: CimTrak
    nexttasks:
      '#none#':
      - "2"
    scriptarguments:
      ObjectDetailId:
        simple: ${inputs.lObjectDetailID}
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 50,
          "y": 230
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
    isoversize: false
    isautoswitchedtoquietmode: false
  "2":
    id: "2"
    taskid: b8690ae1-c523-44df-863f-05478638ec67
    type: condition
    task:
      id: b8690ae1-c523-44df-863f-05478638ec67
      version: -1
      name: Check if file is malicious
      description: "Gets a value and return it. This is to be used in playbook conditional tasks - get a value from incident field, label or context, and act accordingly. \nIf an array is returned. the first value will be the decision making value."
      type: condition
      iscommand: false
      brand: ""
    nexttasks:
      '#default#':
      - "11"
      File is malicious:
      - "4"
      File is not malicious:
      - "3"
    separatecontext: false
    conditions:
    - label: File is not malicious
      condition:
      - - operator: isEqualNumber
          left:
            value:
              complex:
                root: CimTrak.FileAnalysis
                filters:
                - - operator: isEqualString
                    left:
                      value:
                        simple: CimTrak.FileAnalysis.analysisEngine
                      iscontext: true
                    right:
                      value:
                        simple: VirusTotal
                accessor: analysisResults.positives
            iscontext: true
          right:
            value:
              simple: "0"
      - - operator: greaterThanOrEqual
          left:
            value:
              complex:
                root: CimTrak.FileAnalysis
                filters:
                - - operator: isEqualString
                    left:
                      value:
                        simple: CimTrak.FileAnalysis.analysisEngine
                      iscontext: true
                    right:
                      value:
                        simple: VirusTotal
                accessor: analysisResults.total
            iscontext: true
          right:
            value:
              simple: "50"
    - label: File is malicious
      condition:
      - - operator: greaterThanOrEqual
          left:
            value:
              complex:
                root: CimTrak.FileAnalysis
                filters:
                - - operator: isEqualString
                    left:
                      value:
                        simple: CimTrak.FileAnalysis.analysisEngine
                      iscontext: true
                    right:
                      value:
                        simple: VirusTotal
                accessor: analysisResults.positives
            iscontext: true
          right:
            value:
              simple: "5"
    view: |-
      {
        "position": {
          "x": 50,
          "y": 410
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
    isoversize: false
    isautoswitchedtoquietmode: false
  "3":
    id: "3"
    taskid: d2e631ce-0b21-48bb-8b67-cd1b812aa70a
    type: regular
    task:
      id: d2e631ce-0b21-48bb-8b67-cd1b812aa70a
      version: -1
      name: add-hash-allow-list MD5
      description: Add Hash to allow list
      script: CimTrak|||add-hash-allow-list
      type: regular
      iscommand: true
      brand: CimTrak
    nexttasks:
      '#none#':
      - "6"
    scriptarguments:
      hash:
        complex:
          root: CimTrak.FileAnalysis.analysisResults
          accessor: md5
          transformers:
          - operator: concat
            args:
              prefix:
                value:
                  simple: 'MD5:'
              suffix: {}
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 320,
          "y": 640
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
    isoversize: false
    isautoswitchedtoquietmode: false
  "4":
    id: "4"
    taskid: a57b71a0-47bf-43d8-815a-3c6f556276e4
    type: regular
    task:
      id: a57b71a0-47bf-43d8-815a-3c6f556276e4
      version: -1
      name: add-hash-deny-list MD5
      description: Add Hash to deny list
      script: CimTrak|||add-hash-deny-list
      type: regular
      iscommand: true
      brand: CimTrak
    nexttasks:
      '#none#':
      - "9"
    scriptarguments:
      hash:
        complex:
          root: CimTrak.FileAnalysis.analysisResults
          accessor: md5
          transformers:
          - operator: concat
            args:
              prefix:
                value:
                  simple: 'MD5:'
              suffix: {}
    separatecontext: false
    view: |-
      {
        "position": {
          "x": -140,
          "y": 640
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
    isoversize: false
    isautoswitchedtoquietmode: false
  "6":
    id: "6"
    taskid: 8ab4c796-e7a2-4e86-8f74-c581733ebe39
    type: regular
    task:
      id: 8ab4c796-e7a2-4e86-8f74-c581733ebe39
      version: -1
      name: add-hash-allow-list SHA256
      description: Add Hash to allow list
      script: CimTrak|||add-hash-allow-list
      type: regular
      iscommand: true
      brand: CimTrak
    nexttasks:
      '#none#':
      - "7"
    scriptarguments:
      hash:
        complex:
          root: CimTrak.FileAnalysis.analysisResults
          accessor: sha256
          transformers:
          - operator: concat
            args:
              prefix:
                value:
                  simple: 'SHA256:'
              suffix: {}
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 320,
          "y": 820
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
    isoversize: false
    isautoswitchedtoquietmode: false
  "7":
    id: "7"
    taskid: a626cbf3-6899-4a3e-865e-18923bf96e8f
    type: regular
    task:
      id: a626cbf3-6899-4a3e-865e-18923bf96e8f
      version: -1
      name: add-hash-allow-list SHA1
      description: Add Hash to allow list
      script: CimTrak|||add-hash-allow-list
      type: regular
      iscommand: true
      brand: CimTrak
    nexttasks:
      '#none#':
      - "8"
    scriptarguments:
      hash:
        complex:
          root: CimTrak.FileAnalysis.analysisResults
          accessor: sha1
          transformers:
          - operator: concat
            args:
              prefix:
                value:
                  simple: 'SHA1:'
              suffix: {}
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 320,
          "y": 1000
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
    isoversize: false
    isautoswitchedtoquietmode: false
  "8":
    id: "8"
    taskid: 1e51916d-c269-4bd7-8979-eae892feae8c
    type: regular
    task:
      id: 1e51916d-c269-4bd7-8979-eae892feae8c
      version: -1
      name: promote-authoritative-baseline-files
      description: Promote baseline files
      script: CimTrak|||promote-authoritative-baseline-files
      type: regular
      iscommand: true
      brand: CimTrak
    scriptarguments:
      ObjectDetaildIds:
        simple: ${inputs.lObjectDetailID}
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 320,
          "y": 1180
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
    isoversize: false
    isautoswitchedtoquietmode: false
  "9":
    id: "9"
    taskid: 426e19eb-865f-4073-8d6e-e35cecac90cc
    type: regular
    task:
      id: 426e19eb-865f-4073-8d6e-e35cecac90cc
      version: -1
      name: add-hash-deny-list SHA256
      description: Add Hash to deny list
      script: CimTrak|||add-hash-deny-list
      type: regular
      iscommand: true
      brand: CimTrak
    nexttasks:
      '#none#':
      - "10"
    scriptarguments:
      hash:
        complex:
          root: CimTrak.FileAnalysis.analysisResults
          accessor: sha256
          transformers:
          - operator: concat
            args:
              prefix:
                value:
                  simple: 'SHA256:'
              suffix: {}
    separatecontext: false
    view: |-
      {
        "position": {
          "x": -140,
          "y": 820
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
    isoversize: false
    isautoswitchedtoquietmode: false
  "10":
    id: "10"
    taskid: 8da41de5-c29f-405b-819f-71d4d4cce995
    type: regular
    task:
      id: 8da41de5-c29f-405b-819f-71d4d4cce995
      version: -1
      name: add-hash-deny-list SHA1
      description: Add Hash to deny list
      script: CimTrak|||add-hash-deny-list
      type: regular
      iscommand: true
      brand: CimTrak
    scriptarguments:
      hash:
        complex:
          root: CimTrak.FileAnalysis.analysisResults
          accessor: sha1
          transformers:
          - operator: concat
            args:
              prefix:
                value:
                  simple: 'SHA1:'
              suffix: {}
    separatecontext: false
    view: |-
      {
        "position": {
          "x": -140,
          "y": 1000
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
    isoversize: false
    isautoswitchedtoquietmode: false
  "11":
    id: "11"
    taskid: 1ae2fee7-75b8-4795-8a82-bafc40451577
    type: regular
    task:
      id: 1ae2fee7-75b8-4795-8a82-bafc40451577
      version: -1
      name: Manually remediate  the incident
      description: "Review the incident to determine if the account activity is malicious.\n\nIf malicious, consider the following:\n* Quarantine the account/ endpoint \n* Revoke the account password\n* Query the account/ IPs logs in the SIEM\n* Block the external IPs in the firewall/ proxy\n* Check the account's privileges and change if needed"
      type: regular
      iscommand: false
      brand: ""
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 780,
          "y": 580
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
    isoversize: false
    isautoswitchedtoquietmode: false
view: |-
  {
    "linkLabelsPosition": {
      "2_11_#default#": 0.79
    },
    "paper": {
      "dimensions": {
        "height": 1225,
        "width": 1300,
        "x": -140,
        "y": 50
      }
    }
  }
inputs:
- key: ""
  value: {}
  required: false
  description: ""
  playbookInputQuery:
    query: ""
    queryEntity: indicators
    results:
    daterange:
      fromdate: 0001-01-01T00:00:00Z
      todate: 0001-01-01T00:00:00Z
      period:
        by: ""
        byto: ""
        byfrom: ""
        tovalue:
        fromvalue:
        field: ""
      fromdatelicenseval: 0001-01-01T00:00:00Z
    runFromLastJobTime: true
- key: lObjectDetailID
  value:
    complex:
      root: ${incident.labels
      accessor: objectDetailId}
  required: false
  description: ""
  playbookInputQuery:
outputs: []
quiet: true
tests:
- No tests (auto formatted)
fromversion: 6.0.0
description: Example to analyze intrusion
