contentitemexportablefields:
  contentitemfields:
    propagationLabels:
    - all
description: |-
  This Playbook simulates a vulnerability scan using the "HelloWorld" sample integration. It's used to demonstrate how to use the GenericPolling mechanism to run jobs that take several seconds or minutes to complete. It is designed to be used as a subplaybook, but you can also use it as a standalone playbook, by providing the ${Endpoint.Hostname} input in the Context.

  Other inputs include the report output format (JSON context or File attached), and the Interval/Timeouts to use for polling the scan status until it's complete.
id: HelloWorld Say Hello
inputs:
- description: Hostname to run the scan against. By default takes ${Endpoint.Hostname}
    from the context as the input.
  key: Hostname
  playbookInputQuery:
  required: true
  value:
    complex:
      accessor: Hostname}
      root: ${Endpoint
- description: 'Output report format: can be "json" (output parsed and written in
    the Context) or "file" (saved as an attachment). By default is "json".'
  key: Report Format
  playbookInputQuery:
  required: true
  value:
    simple: json
- description: How often to check for the scan to be completed (minutes)
  key: Interval
  playbookInputQuery:
  required: true
  value:
    simple: "1"
- description: How long to wait for the scan to be completed before timing out (minutes)
  key: Timeout
  playbookInputQuery:
  required: true
  value:
    simple: "15"
name: HelloWorld Say Hello
outputs:
- contextPath: HelloWorld.Scan.entity.entity-id
  description: Scanned entity ID.
- contextPath: HelloWorld.Scan.entity.ip_address
  description: Scanned entity IP address.
- contextPath: HelloWorld.Scan.entity.type
  description: Scanned entity type.
- contextPath: HelloWorld.Scan.entity.vulnerability_status
  description: Scanned entity vulnerability status.
- contextPath: HelloWorld.Scan.entity.vulns
  description: Scanned entity CVE.
- contextPath: CVE.ID
  description: The ID of the CVE.
- contextPath: InfoFile.EntryID
  description: The EntryID of the report file.
- contextPath: InfoFile.Extension
  description: The extension of the report file.
- contextPath: InfoFile.Name
  description: The name of the report file.
- contextPath: InfoFile.Info
  description: The info of the report file.
- contextPath: InfoFile.Size
  description: The size of the report file.
- contextPath: InfoFile.Type
  description: The type of the report file.
starttaskid: "0"
tasks:
  "0":
    id: "0"
    ignoreworker: false
    nexttasks:
      '#none#':
      - "5"
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      id: d42bb08f-8bdc-4882-8da0-bc8107369db7
      iscommand: false
      name: ""
      version: -1
      description: ''
    taskid: d42bb08f-8bdc-4882-8da0-bc8107369db7
    timertriggers: []
    type: start
    view: |-
      {
        "position": {
          "x": 265,
          "y": 50
        }
      }
  "1":
    id: "1"
    ignoreworker: false
    nexttasks:
      '#none#':
      - "2"
    note: false
    quietmode: 0
    scriptarguments:
      name:
        simple: rsagi
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      description: Hello command - prints hello to anyone.
      id: 991ad305-af30-49d0-892a-84b980042c44
      iscommand: true
      name: Say Hello
      script: '|||helloworld-say-hello-new'
      type: regular
      version: -1
    taskid: 991ad305-af30-49d0-892a-84b980042c44
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 50,
          "y": 370
        }
      }
  "2":
    id: "2"
    ignoreworker: false
    loop:
      exitCondition: ""
      iscommand: false
      max: 100
      wait: 1
    nexttasks:
      '#none#':
      - "3"
    note: false
    quietmode: 0
    scriptarguments:
      AdditionalPollingCommandArgNames: {}
      AdditionalPollingCommandArgValues: {}
      Ids:
        simple: ${HelloWorld.Scan.scan_id}
      Interval:
        simple: ${inputs.Interval}
      PollingCommandArgName:
        simple: scan_id
      PollingCommandName:
        simple: helloworld-scan-status
      Timeout:
        simple: ${inputs.Timeout}
      dt:
        simple: HelloWorld.Scan(val.status !== 'COMPLETE').scan_id
    separatecontext: true
    skipunavailable: false
    task:
      brand: ""
      description: |-
        Use this playbook as a sub-playbook to block execution of the master playbook until a remote action is complete.
        This playbook implements polling by continuously running the command in Step \#2 until the operation completes.
        The remote action should have the following structure:

        1. Initiate the operation.
        2. Poll to check if the operation completed.
        3. (optional) Get the results of the operation.
      id: 4dba5fa5-3839-434d-874c-d5239946b953
      iscommand: false
      name: GenericPolling
      playbookId: GenericPolling
      type: playbook
      version: -1
    taskid: 4dba5fa5-3839-434d-874c-d5239946b953
    timertriggers: []
    type: playbook
    view: |-
      {
        "position": {
          "x": 50,
          "y": 545
        }
      }
  "3":
    id: "3"
    ignoreworker: false
    nexttasks:
      '#none#':
      - "4"
    note: false
    quietmode: 0
    scriptarguments:
      alert_id:
        simple: "1"
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      description: Retrieve alert extra data by ID.
      id: a3aade51-e07f-4d0c-81f8-65345be13211
      iscommand: true
      name: Retrieve HelloWorld Scan Results
      script: '|||helloworld-get-alert-new'
      type: regular
      version: -1
    taskid: a3aade51-e07f-4d0c-81f8-65345be13211
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 50,
          "y": 720
        }
      }
  "4":
    id: "4"
    ignoreworker: false
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      id: 5e316da3-3769-46fb-8da3-e12bac82c696
      iscommand: false
      name: Done
      type: title
      version: -1
      description: ''
    taskid: 5e316da3-3769-46fb-8da3-e12bac82c696
    timertriggers: []
    type: title
    view: |-
      {
        "position": {
          "x": 265,
          "y": 895
        }
      }
  "5":
    conditions:
    - condition:
      - - left:
            iscontext: true
            value:
              simple: inputs.Hostname
          operator: isNotEmpty
      label: "true"
    id: "5"
    ignoreworker: false
    nexttasks:
      '#default#':
      - "6"
      "true":
      - "1"
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      description: Check if the input Hostname is valid (i.e. is not Empty), do not
        run the scan otherwise.
      id: 40eb7cdf-5e62-4e85-89fa-fca448fb7e6b
      iscommand: false
      name: Is Hostname set?
      type: condition
      version: -1
    taskid: 40eb7cdf-5e62-4e85-89fa-fca448fb7e6b
    timertriggers: []
    type: condition
    view: |-
      {
        "position": {
          "x": 265,
          "y": 195
        }
      }
  "6":
    id: "6"
    ignoreworker: false
    nexttasks:
      '#none#':
      - "4"
    note: false
    quietmode: 0
    scriptarguments:
      message:
        simple: Hostname is not set, cannot run the playbook!
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      description: Prints an error entry with a given message
      id: 9bb9d3c8-81bb-460b-8219-bf93a46d6c21
      iscommand: false
      name: Print Error New
      scriptName: PrintErrorEntry
      type: regular
      version: -1
    taskid: 9bb9d3c8-81bb-460b-8219-bf93a46d6c21
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 480,
          "y": 720
        }
      }
version: -1
view: |-
  {
    "linkLabelsPosition": {},
    "paper": {
      "dimensions": {
        "height": 910,
        "width": 810,
        "x": 50,
        "y": 50
      }
    }
  }
tests:
- No tests (auto formatted)
fromversion: 6.0.0
