contentitemexportablefields:
  contentitemfields:
    propagationLabels:
    - all
description: This is a playbook which will handle the alerts coming from the Hello
  World service
id: Handle Hello World Alert v2
inputs:
- description: Alert ID to retrieve details for. By default retrieves from the HelloWorld
    ID custom field in the HelloWorld incident type
  key: AlertID
  playbookInputQuery:
  required: false
  value:
    simple: ${incident.helloworldid}
name: Handle Hello World Alert v2
outputs: []
starttaskid: "0"
tasks:
  "0":
    id: "0"
    ignoreworker: false
    nexttasks:
      '#none#':
      - "1"
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      id: 55b6fa84-3501-43e2-872b-570b688fd312
      iscommand: false
      name: ""
      version: -1
      description: ''
    taskid: 55b6fa84-3501-43e2-872b-570b688fd312
    timertriggers: []
    type: start
    view: |-
      {
        "position": {
          "x": 50,
          "y": 50
        }
      }
  "1":
    id: "1"
    ignoreworker: false
    note: false
    quietmode: 0
    scriptarguments:
      alert_id:
        simple: ${inputs.AlertID}
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      description: Retrieve alert extra data by ID.
      id: 92bfbbe9-0e30-4b5b-8d08-0b8ec0efcca3
      iscommand: true
      name: Get alert details v2
      script: '|||helloworld-get-alert-new'
      type: regular
      version: -1
    taskid: 92bfbbe9-0e30-4b5b-8d08-0b8ec0efcca3
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 50,
          "y": 195
        }
      }
version: -1
view: |-
  {
    "linkLabelsPosition": {},
    "paper": {
      "dimensions": {
        "height": 240,
        "width": 380,
        "x": 50,
        "y": 50
      }
    }
  }
tests:
- No tests (auto formatted)
fromversion: 6.0.0
