contentitemexportablefields:
  contentitemfields:
    fromServerVersion: ""
    itemVersion: ""
    packID: fbc62e49-d012-44d3-804f-2d02413326f4
    propagationLabels:
    - all
    toServerVersion: ""
id: 58fd5b7a-1301-4b65-85be-f350edc29f7a
inputs:
- description: ""
  key: DeviceGroup
  playbookInputQuery: null
  required: true
  value:
    simple: demisto
- description: ""
  key: ClusterName
  playbookInputQuery: null
  required: true
  value:
    simple: gke_cps-containers-dev_us-central1-c_gunjan-cn-xsoar
- description: True if the playbook should automatically commit after pushing the
    policy changes, False otherwise. Default is False.
  key: AutoCommit
  playbookInputQuery: null
  required: true
  value:
    simple: "False"
name: PAN-OS Update Policy from Kubernetes Network Policy
outputs: []
starttaskid: "0"
tasks:
  "0":
    id: "0"
    ignoreworker: false
    nexttasks:
      '#none#':
      - "33"
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      id: 0a58beca-2997-45ee-8f85-83bc5a3be746
      iscommand: false
      name: ""
      version: -1
    taskid: 0a58beca-2997-45ee-8f85-83bc5a3be746
    timertriggers: []
    type: start
    view: |-
      {
        "position": {
          "x": 387.5,
          "y": -135
        }
      }
  "4":
    id: "4"
    ignoreworker: false
    nexttasks:
      '#none#':
      - "32"
    note: false
    quietmode: 0
    scriptarguments:
      assetid: {}
      closeNotes: {}
      closeReason: {}
      emailclassification: {}
      id: {}
      phishingsubtype: {}
    separatecontext: false
    skipunavailable: false
    task:
      brand: Builtin
      description: commands.local.cmd.close.inv
      id: 24ef58c6-ab69-4014-8cd1-ca4c3a3d7dc1
      iscommand: true
      name: Close incident
      script: Builtin|||closeInvestigation
      type: regular
      version: -1
    taskid: 24ef58c6-ab69-4014-8cd1-ca4c3a3d7dc1
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 277.5,
          "y": 2745
        }
      }
  "5":
    id: "5"
    ignoreworker: false
    nexttasks:
      '#none#':
      - "17"
      - "29"
    note: false
    quietmode: 0
    scriptarguments:
      ClusterName:
        simple: ${inputs.ClusterName}
      KubernetesNetworkPolicy:
        simple: ${incident.kubernetesnetworkpolicy}
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      id: 92b4ae3f-84f5-4a72-8fa7-2661aedf5195
      iscommand: false
      name: Derive PAN-OS objects from Kubernetes policy
      script: 732fe79e-48ac-4e61-ab3d-bb68323c7adc
      type: regular
      version: -1
    taskid: 92b4ae3f-84f5-4a72-8fa7-2661aedf5195
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 387.5,
          "y": 360
        }
      }
  "6":
    id: "6"
    ignoreworker: false
    nexttasks:
      '#none#':
      - "9"
    note: false
    quietmode: 0
    scriptarguments:
      action:
        simple: allow
      application:
        simple: ${ConvertedPolicy.Rule.Application}
      category: {}
      description:
        simple: ${ConvertedPolicy.Rule.Description}
      destination:
        simple: ${ConvertedPolicy.Rule.Dst}
      destination_zone:
        simple: ${ConvertedPolicy.Rule.ToZone}
      device-group:
        simple: ${inputs.DeviceGroup}
      disable: {}
      log_forwarding: {}
      negate_destination: {}
      negate_source: {}
      pre_post:
        simple: post-rulebase
      rulename:
        simple: ${ConvertedPolicy.Rule.Name}
      service: {}
      source:
        simple: ${ConvertedPolicy.Rule.Src}
      source_user: {}
      source_zone:
        simple: ${ConvertedPolicy.Rule.FromZone}
      tags:
        simple: xsoar
      target: {}
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      description: Creates a policy rule.
      id: 23754f31-9708-4383-8f80-ebea0b74b2b4
      iscommand: true
      name: PAN-OS - Create rules
      script: '|||panorama-create-rule'
      type: regular
      version: -1
    taskid: 23754f31-9708-4383-8f80-ebea0b74b2b4
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 277.5,
          "y": 2100
        }
      }
  "7":
    id: "7"
    ignoreworker: false
    nexttasks:
      '#none#':
      - "5"
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      id: 81e01ef7-3b82-41ba-8531-22f3f7a34353
      iscommand: false
      name: Analyze Network Policy
      type: title
      version: -1
    taskid: 81e01ef7-3b82-41ba-8531-22f3f7a34353
    timertriggers: []
    type: title
    view: |-
      {
        "position": {
          "x": 387.5,
          "y": 225
        }
      }
  "9":
    conditions:
    - condition:
      - - left:
            iscontext: true
            value:
              simple: inputs.AutoCommit
          operator: isEqualString
          right:
            value:
              simple: "True"
      label: "yes"
    id: "9"
    ignoreworker: false
    nexttasks:
      '#default#':
      - "4"
      "yes":
      - "10"
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      id: c49ceaaf-353a-45b9-80dc-db4e334d6cd4
      iscommand: false
      name: Auto-Commit?
      type: condition
      version: -1
    taskid: c49ceaaf-353a-45b9-80dc-db4e334d6cd4
    timertriggers: []
    type: condition
    view: |-
      {
        "position": {
          "x": 277.5,
          "y": 2395
        }
      }
  "10":
    id: "10"
    ignoreworker: false
    nexttasks:
      '#none#':
      - "4"
    note: false
    quietmode: 0
    separatecontext: true
    skipunavailable: false
    task:
      brand: ""
      description: Commit the PAN-OS Panorama or Firewall configuration.\nIf specified
        as Panorama, it also pushes the Policies to the specified Device Group in
        the instance.
      id: 3ef1993e-d3ed-4f28-8f98-d17623a1b46c
      iscommand: false
      name: PAN-OS Commit Configuration
      playbookId: PAN-OS Commit Configuration
      type: playbook
      version: -1
    taskid: 3ef1993e-d3ed-4f28-8f98-d17623a1b46c
    timertriggers: []
    type: playbook
    view: |-
      {
        "position": {
          "x": 580,
          "y": 2570
        }
      }
  "17":
    id: "17"
    ignoreworker: false
    nexttasks:
      '#none#':
      - "24"
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      id: 39184869-204a-43ba-81fa-7a65813ce2b0
      iscommand: false
      name: DAG Creation
      type: title
      version: -1
    taskid: 39184869-204a-43ba-81fa-7a65813ce2b0
    timertriggers: []
    type: title
    view: |-
      {
        "position": {
          "x": 392.5,
          "y": 545
        }
      }
  "21":
    id: "21"
    ignoreworker: false
    nexttasks:
      '#none#':
      - "28"
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      id: ccae8dbc-41e6-4ea6-8905-7714d9a139b1
      iscommand: false
      name: Rule creation
      type: title
      version: -1
    taskid: ccae8dbc-41e6-4ea6-8905-7714d9a139b1
    timertriggers: []
    type: title
    view: |-
      {
        "position": {
          "x": 277.5,
          "y": 1440
        }
      }
  "23":
    id: "23"
    ignoreworker: false
    nexttasks:
      '#none#':
      - "21"
    note: false
    quietmode: 0
    scriptarguments:
      addresses: {}
      description:
        simple: ${ConvertedPolicy.DAG.Description}
      device-group:
        simple: ${inputs.DeviceGroup}
      match:
        simple: ${ConvertedPolicy.DAG.Match}
      name:
        simple: ${ConvertedPolicy.DAG.Name}
      tags: {}
      type:
        simple: dynamic
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      description: Creates a static or dynamic address group.
      id: be3ab9dc-f021-4eb6-8973-91060f98483d
      iscommand: true
      name: Create DAGs
      script: '|||panorama-create-address-group'
      type: regular
      version: -1
    taskid: be3ab9dc-f021-4eb6-8973-91060f98483d
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 880,
          "y": 1260
        }
      }
  "24":
    conditions:
    - condition:
      - - left:
            iscontext: true
            value:
              complex:
                accessor: DAG
                root: ConvertedPolicy
          operator: isExists
      label: "yes"
    id: "24"
    ignoreworker: false
    nexttasks:
      '#default#':
      - "21"
      "yes":
      - "26"
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      id: e5ded543-bcd1-47e6-8290-26174a78d8a5
      iscommand: false
      name: Any DAGs in the policy?
      type: condition
      version: -1
    taskid: e5ded543-bcd1-47e6-8290-26174a78d8a5
    timertriggers: []
    type: condition
    view: |-
      {
        "position": {
          "x": 387.5,
          "y": 670
        }
      }
  "26":
    id: "26"
    ignoreworker: false
    nexttasks:
      '#none#':
      - "31"
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      id: 71f13900-19a2-4ac5-8adb-4daf81326028
      iscommand: false
      name: Create PAN-OS Dynamic Address Groups
      type: title
      version: -1
    taskid: 71f13900-19a2-4ac5-8adb-4daf81326028
    timertriggers: []
    type: title
    view: |-
      {
        "position": {
          "x": 880,
          "y": 860
        }
      }
  "28":
    id: "28"
    ignoreworker: false
    nexttasks:
      '#none#':
      - "6"
    note: false
    quietmode: 0
    scriptarguments:
      device-group:
        simple: ${inputs.DeviceGroup}
      pre_post:
        simple: post-rulebase
      rulename:
        simple: ${ConvertedPolicy.Rule.Name}
    separatecontext: false
    skipunavailable: false
    task:
      brand: Panorama
      description: Deletes a policy rule.
      id: 32b74add-714a-48aa-83fe-36c617ce03e4
      iscommand: true
      name: Delete rule
      script: Panorama|||panorama-delete-rule
      type: regular
      version: -1
    taskid: 32b74add-714a-48aa-83fe-36c617ce03e4
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 277.5,
          "y": 1650
        }
      }
  "29":
    id: "29"
    ignoreworker: false
    nexttasks:
      '#none#':
      - "30"
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      id: 5979a78e-fa9e-4751-826c-22247e920326
      iscommand: false
      name: Service Creation
      type: title
      version: -1
    taskid: 5979a78e-fa9e-4751-826c-22247e920326
    timertriggers: []
    type: title
    view: |-
      {
        "position": {
          "x": -120,
          "y": 545
        }
      }
  "30":
    id: "30"
    ignoreworker: false
    nexttasks:
      '#none#':
      - "21"
    note: false
    quietmode: 0
    scriptarguments:
      description: {}
      destination_port:
        complex:
          accessor: Port
          root: ConvertedPolicy.Services
          transformers:
          - operator: Stringify
      device-group:
        simple: ${inputs.DeviceGroup}
      name:
        complex:
          accessor: Name
          root: ConvertedPolicy.Services
      protocol:
        complex:
          accessor: Protocol
          root: ConvertedPolicy.Services
      source_port: {}
      tags: {}
    separatecontext: false
    skipunavailable: false
    task:
      brand: Panorama
      description: Creates a service.
      id: 7c81e7c1-7da2-41ed-8786-731054b861fb
      iscommand: true
      name: Create Service Objects
      script: Panorama|||panorama-create-service
      type: regular
      version: -1
    taskid: 7c81e7c1-7da2-41ed-8786-731054b861fb
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": -110,
          "y": 660
        }
      }
  "31":
    conditions:
    - condition:
      - - left:
            iscontext: true
            value:
              simple: ConvertedPolicy.DAG.Name
          operator: isExists
      label: "yes"
    id: "31"
    ignoreworker: false
    nexttasks:
      '#default#':
      - "21"
      "yes":
      - "23"
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      id: 2105a1dc-1638-4d38-843f-a25b087dfd64
      iscommand: false
      name: Any DAGs to create?
      type: condition
      version: -1
    taskid: 2105a1dc-1638-4d38-843f-a25b087dfd64
    timertriggers: []
    type: condition
    view: |-
      {
        "position": {
          "x": 880,
          "y": 1010
        }
      }
  "32":
    id: "32"
    ignoreworker: false
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      id: 49d5a81a-db85-48b9-865b-972c18ebe491
      iscommand: false
      name: Done
      type: title
      version: -1
    taskid: 49d5a81a-db85-48b9-865b-972c18ebe491
    timertriggers: []
    type: title
    view: |-
      {
        "position": {
          "x": 277.5,
          "y": 2930
        }
      }
  "33":
    id: "33"
    ignoreworker: false
    nexttasks:
      '#none#':
      - "7"
    note: false
    quietmode: 0
    scriptarguments:
      accountid: {}
      accountname: {}
      addLabels: {}
      agentid: {}
      app: {}
      appendMultiSelect: {}
      assetid: {}
      attachmentcount: {}
      attachmentextension: {}
      attachmenthash: {}
      attachmentid: {}
      attachmentname: {}
      attachmentsize: {}
      attachmenttype: {}
      blockedaction: {}
      bugtraq: {}
      city: {}
      closeNotes: {}
      closeReason: {}
      commandline: {}
      country: {}
      criticalassets: {}
      customFields: {}
      cve: {}
      cvss: {}
      dbotMirrorDirection: {}
      dbotMirrorId: {}
      dbotMirrorInstance: {}
      dbotMirrorTags: {}
      dbotprediction: {}
      dbotpredictionprobability: {}
      dbottextsuggestionhighlighted: {}
      deleteEmptyField: {}
      dest: {}
      desthostname: {}
      destinationhostname: {}
      destinationip: {}
      destinationnetwork: {}
      destinationport: {}
      destntdomain: {}
      destos: {}
      details: {}
      detectedexternalhosts: {}
      detectedexternalips: {}
      detectedinternalhosts: {}
      detectedinternalips: {}
      detectedusers: {}
      detectionendtime: {}
      detectionid: {}
      detectionupdatetime: {}
      detectionurl: {}
      devicegroup:
        simple: ${inputs.DeviceGroup}
      devicehash: {}
      devicename: {}
      duration: {}
      emailauthenticitycheck: {}
      emailbcc: {}
      emailbody: {}
      emailbodyformat: {}
      emailbodyhtml: {}
      emailcc: {}
      emailclassification: {}
      emailclientname: {}
      emailfrom: {}
      emailheaders: {}
      emailhtml: {}
      emailinreplyto: {}
      emailkeywords: {}
      emailmessageid: {}
      emailreceived: {}
      emailreplyto: {}
      emailreturnpath: {}
      emailsenderip: {}
      emailsize: {}
      emailsource: {}
      emailsubject: {}
      emailto: {}
      emailtocount: {}
      emailurlclicked: {}
      employeedisplayname: {}
      employeeemail: {}
      employeemanageremail: {}
      eventid: {}
      eventtype: {}
      externaladdresses: {}
      filehash: {}
      filename: {}
      filepath: {}
      filesize: {}
      firstname: {}
      firstseen: {}
      helloworldid: {}
      helloworldstatus: {}
      helloworldtype: {}
      hostname: {}
      id: {}
      infectedhosts: {}
      internaladdresses: {}
      investigationstage: {}
      isolated: {}
      kubernetesclustername:
        simple: ${inputs.ClusterName}
      kubernetesnamespace: {}
      kubernetesnetworkpolicy: {}
      kubernetesnetworkpolicyname: {}
      kubernetesresourceversion: {}
      labels: {}
      lastmodifiedby: {}
      lastmodifiedon: {}
      lastname: {}
      lastseen: {}
      logsource: {}
      macaddress: {}
      maliciousbehavior: {}
      malwarefamily: {}
      mobiledevicemodel: {}
      name: {}
      occurred: {}
      os: {}
      osversion: {}
      owner: {}
      parentprocessid: {}
      phase: {}
      phishingsubtype: {}
      phonenumber: {}
      pid: {}
      policydeleted: {}
      policydescription: {}
      policydetails: {}
      policyid: {}
      policyrecommendation: {}
      policyremediable: {}
      policyseverity: {}
      policytype: {}
      prismacloudcomputeactivitytype: {}
      prismacloudcomputeappid: {}
      prismacloudcomputecategory: {}
      prismacloudcomputecollections: {}
      prismacloudcomputecommand: {}
      prismacloudcomputecontainer: {}
      prismacloudcomputecredentialid: {}
      prismacloudcomputedistribution: {}
      prismacloudcomputeerror: {}
      prismacloudcomputeforensic: {}
      prismacloudcomputefqdn: {}
      prismacloudcomputefunction: {}
      prismacloudcomputehost: {}
      prismacloudcomputeimage: {}
      prismacloudcomputeinteractive: {}
      prismacloudcomputekubernetesresource: {}
      prismacloudcomputelabels: {}
      prismacloudcomputeline: {}
      prismacloudcomputelogfile: {}
      prismacloudcomputemarkdown: {}
      prismacloudcomputemessage: {}
      prismacloudcomputeproject: {}
      prismacloudcomputeprotected: {}
      prismacloudcomputeprovider: {}
      prismacloudcomputerawalertjson: {}
      prismacloudcomputeregion: {}
      prismacloudcomputeregistry: {}
      prismacloudcomputerule: {}
      prismacloudcomputeruntime: {}
      prismacloudcomputeservice: {}
      prismacloudcomputeservicetype: {}
      prismacloudcomputetotal: {}
      prismacloudcomputetype: {}
      prismacloudcomputeuser: {}
      protocol: {}
      protocols: {}
      quarantined: {}
      rating: {}
      region: {}
      regionid: {}
      replacePlaybook: {}
      reporteremailaddress: {}
      resourceid: {}
      resourcename: {}
      resourcetype: {}
      riskrating: {}
      riskscore: {}
      roles: {}
      samaccountname: {}
      severity: {}
      signature: {}
      skuname: {}
      skutier: {}
      sla: {}
      slaField: {}
      sourcehostname: {}
      sourceip: {}
      sourcenetwork: {}
      sourceport: {}
      sourceusername: {}
      src: {}
      srchostname: {}
      srcntdomain: {}
      srcos: {}
      srcuser: {}
      subtype: {}
      systems: {}
      targetfirewallversion: {}
      tenantname: {}
      terminatedaction: {}
      threatactor: {}
      triggeredsecurityprofile: {}
      type: {}
      uniqueports: {}
      urlsslverification: {}
      user: {}
      useraccountcontrol: {}
      username: {}
      vendorid: {}
      vendorproduct: {}
      vulnerabilitycategory: {}
    separatecontext: false
    skipunavailable: false
    task:
      brand: Builtin
      description: commands.local.cmd.set.incident
      id: 05b6fcd3-e993-4714-8ebb-77a8def99450
      iscommand: true
      name: Set incident fields
      script: Builtin|||setIncident
      type: regular
      version: -1
    taskid: 05b6fcd3-e993-4714-8ebb-77a8def99450
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 387.5,
          "y": 10
        }
      }
version: -1
view: |-
  {
    "linkLabelsPosition": {
      "24_21_#default#": 0.32,
      "9_10_yes": 0.65
    },
    "paper": {
      "dimensions": {
        "height": 3130,
        "width": 1380,
        "x": -120,
        "y": -135
      }
    }
  }
