contentitemexportablefields:
  contentitemfields:
    fromServerVersion: ""
    itemVersion: ""
    packID: 25043b93-4265-49a0-8858-04aed0ec4edd
    propagationLabels:
    - all
    toServerVersion: ""
description: Example on how to run a compliance scan for an agent based on IP address
id: CimTrak - Example - Scan Compliance By IP
inputs:
- description: ""
  key: IP
  playbookInputQuery: null
  required: false
  value: {}
name: CimTrak - Example - Scan Compliance By IP
outputs: []
starttaskid: "0"
tasks:
  "0":
    id: "0"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "1"
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      id: 81e710f8-1a3a-4ca6-8ed3-1d7d9fc41145
      iscommand: false
      name: ""
      version: -1
    taskid: 81e710f8-1a3a-4ca6-8ed3-1d7d9fc41145
    timertriggers: []
    type: start
    view: |-
      {
        "position": {
          "x": 450,
          "y": 50
        }
      }
  "1":
    id: "1"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "3"
    note: false
    quietmode: 0
    scriptarguments:
      ip:
        simple: ${inputs.IP}
    separatecontext: false
    skipunavailable: false
    task:
      brand: CimTrak
      description: Get agent object from ip address
      id: c302d19c-747f-49e2-8d42-8185da19308e
      iscommand: true
      name: get-agent-object-by-ip
      script: CimTrak|||get-agent-object-by-ip
      type: regular
      version: -1
    taskid: c302d19c-747f-49e2-8d42-8185da19308e
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 450,
          "y": 230
        }
      }
  "2":
    id: "2"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    note: false
    quietmode: 0
    scriptarguments:
      objectId:
        simple: ${CimTrak.Objects.objectId}
    separatecontext: false
    skipunavailable: false
    task:
      brand: CimTrak
      description: Launch compliance scan for object and return results
      id: 76012f52-b420-44bc-814e-98e7e2de0715
      iscommand: true
      name: compliance-scan-with-summary
      script: CimTrak|||compliance-scan-with-summary
      type: regular
      version: -1
    taskid: 76012f52-b420-44bc-814e-98e7e2de0715
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 450,
          "y": 640
        }
      }
  "3":
    id: "3"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "2"
    note: false
    quietmode: 0
    scriptarguments:
      ObjectSubType:
        simple: "10"
      ObjectType:
        simple: "3"
      ParentId:
        simple: ${CimTrak.Object.objectId}
    separatecontext: false
    skipunavailable: false
    task:
      brand: CimTrak
      description: Retrieves a list of objects.
      id: 2f1c4ef0-82c8-4300-879b-613a7153bc76
      iscommand: true
      name: get-objects
      script: CimTrak|||get-objects
      type: regular
      version: -1
    taskid: 2f1c4ef0-82c8-4300-879b-613a7153bc76
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 450,
          "y": 430
        }
      }
version: -1
view: |-
  {
    "linkLabelsPosition": {},
    "paper": {
      "dimensions": {
        "height": 685,
        "width": 380,
        "x": 450,
        "y": 50
      }
    }
  }
